#!/usr/bin/env python3
"""Evaluation harness — DO NOT MODIFY.

Replace this with your evaluation infrastructure. It should:
1. Load your test data (generated by prepare.py)
2. Import and call the function(s) from editable.py
3. Calculate your scalar metric
4. Print a greppable RESULT line

Usage:
    python harness.py evaluate   — run full evaluation
    python harness.py baseline   — show baseline metric (no optimization)
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent


def load_data():
    """Load test data. Replace with your data loading logic."""
    data_path = ROOT / "data" / "test.jsonl"
    items = []
    with open(data_path) as f:
        for line in f:
            if line.strip():
                items.append(json.loads(line))
    return items


def evaluate(use_editable: bool = True):
    """Run evaluation. Replace with your scoring logic."""
    data = load_data()

    if use_editable:
        from editable import process

    total_score = 0.0
    for item in data:
        if use_editable:
            result = process(item)
        else:
            result = item  # Baseline

        # Replace with your scoring logic
        score = 1.0  # Placeholder
        total_score += score

    metric = total_score / len(data) if data else 0
    print(f"RESULT: metric={metric:.4f} items={len(data)}")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "evaluate"
    if cmd == "evaluate":
        evaluate(use_editable=True)
    elif cmd == "baseline":
        evaluate(use_editable=False)
    else:
        print(f"Usage: python harness.py [evaluate|baseline]")
